@apiKey = fHuDB_ZYQ6JQxhYt2Mh4FSxTPrRu4GPy
@bookId = 8aeef6af-9856-4553-9247-3806ca19c033


### login ---------------------------------------------------

POST {{baseUrl}}?r=api/auth/login
Content-Type: application/json

{
    "username": "bob",
    "password": "bob"
}


### Check Token
GET {{baseUrl}}?r=api/auth/check-api-key&token={{apiKey}}

### TICKET : create --------------------------------------------
POST {{baseUrl}}?r=api/ticket/create&id={{bookId}}
X-Api-Key: {{apiKey}}
Content-Type: application/json

{
    "departureDate": "bob"
}

### Ticket : view
GET {{baseUrl}}?r=api/ticket&id={{bookId}}&expand=book
X-Api-Key: {{apiKey}}


### Ticket : view not found
GET {{baseUrl}}?r=api/ticket&id=NOT_FOUND
X-Api-Key: {{apiKey}}

### Email Ticket
GET {{baseUrl}}?r=api/ticket/send-email&id={{bookId}}
X-Api-Key: {{apiKey}}




### SEARCH ISBN ---------------------------------------------------
GET {{baseUrl}}?r=api/isbn-service/search&isbn=9782070344130
X-Api-Key: {{apiKey}}

### SEARCH BOOK DESCRIPTION  (ISBN)
GET {{baseUrl}}?r=api/isbn-service/description&isbn=9782070344130
X-Api-Key: {{apiKey}}

### USER-BOOK - Create ---------------------------------------------
POST {{baseUrl}}?r=api/user-book/create
Content-Type:application/json
X-Api-Key: {{apiKey}}

{
    "book": {
        "title": "___Babylon99",
        "author": "Inconnu",
        "isbn" : "1224"
    },
    "userBook" : {
        "read_status": 2
    }
}

### USER-BOOK - Read All 
GET {{baseUrl}}?r=api/user-book&expand=book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### USER-BOOK - View One
GET {{baseUrl}}?r=api/user-book/view&id=7&expand=book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### USER-BOOK - Update One
PUT {{baseUrl}}?r=api/user-book/update&id=e767cf3d-2119-4ea3-8b76-7a31f7823698
Content-Type:application/json
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "title": "**Babylon 99",
    "author": "Bobby"
}

### USER-BOOK - delete One
DELETE {{baseUrl}}?r=api/user-book/delete&id=7
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

