@apiKey = uBm5GB7CHhBr18TKO6ORC_Ws-fFlABc4

### login

POST {{baseUrl}}?r=api/auth/login
Content-Type: application/json

{
    "username": "bob",
    "password": "bob"
}

### Check Token
GET {{baseUrl}}?r=api/auth/check-api-key&token={{apiKey}}


### Create
POST {{baseUrl}}?r=api/user-book/create
Content-Type:application/json
X-Api-Key: {{apiKey}}

{
    "title": "___Babylon99",
    "author": "Inconnu"
}

### Read All
GET {{baseUrl}}?r=api/user-book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### View One
GET {{baseUrl}}?r=api/user-book/view&id=7&expand=book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### Update One
PUT {{baseUrl}}?r=api/user-book/update&id=7
Content-Type:application/json
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "title": "**Babylon 99",
    "author": "Bobby"
}

### delete One
DELETE {{baseUrl}}?r=api/user-book/delete&id=7
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

