@apiKey = hKbbiGgOO4gPurvbJAbpw6r5-pBvL-N1

### login

POST {{baseUrl}}?r=api/auth/login
Content-Type: application/json

{
    "username": "bob",
    "password": "bob"
}

### Read All
GET {{baseUrl}}?r=api/book
X-Api-Key: {{apiKey}}

### Read All - only field title
GET {{baseUrl}}?r=api/book&fields=title
X-Api-Key: {{apiKey}}

### Read One by Id
GET {{baseUrl}}?r=api/book/view&id=1
X-Api-Key: {{apiKey}}

### Read One by Id, only field title
GET {{baseUrl}}?r=api/book/view&id=1&fields=title
X-Api-Key: {{apiKey}}

### show header info
HEAD {{baseUrl}}?r=api/book
X-Api-Key: {{apiKey}}

### Create _____DISABLED______
POST {{baseUrl}}?r=api/book/create
Content-Type:application/json
X-Api-Key: {{apiKey}}

{
    "title": "__xxx_Babylon99",
    "author": "Inconnu"
}

### Update _____DISABLED______
# id query param is required - id property is optional unless 
# it should also be updated
PATCH {{baseUrl}}?r=api/book/update&id=f6a9fca2-f723-4914-94a9-7644e8a0fe4b
Content-Type:application/json
X-Api-Key: {{apiKey}}

{
    "title": "...Babylon99...",
    "author": "Inconnu"
}

### Delete _____DISABLED______
DELETE {{baseUrl}}?r=api/book/delete&id=3
X-Api-Key: {{apiKey}}
