@apiKey = dzYL99feenXX0HP8QXmUE1uON_sq7_Aj
@bookId = 8d9c9a1d-308f-4c9d-8880-40d210dce55a


### login ---------------------------------------------------

POST {{baseUrl}}?r=api/auth/login
Content-Type: application/json

{
    "username": "user2",
    "password": "Password1"
}


### Check Token
GET {{baseUrl}}?r=api/auth/check-api-key&token={{apiKey}}

### TRACKER : read --------------------------------------------
GET {{baseUrl}}?r=api/tracker&id={{bookId}}


### TICKET : create --------------------------------------------
POST {{baseUrl}}?r=api/ticket/create&id={{bookId}}
X-Api-Key: {{apiKey}}
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "departureDateTime": "2021-09-09T12:43:13.220Z",
    "from": "Some place"
}

### Ticket : view
GET {{baseUrl}}?r=api/ticket&id={{bookId}}&expand=book
X-Api-Key: {{apiKey}}

### Ticket : view not found
GET {{baseUrl}}?r=api/ticket&id=NOT_FOUND
X-Api-Key: {{apiKey}}

### Ticket : Boarding
POST  {{baseUrl}}?r=api/ticket/boarding&id={{bookId}}
X-Api-Key: {{apiKey}}

### Ticket : Delete
DELETE  {{baseUrl}}?r=api/ticket/delete&id={{bookId}}
X-Api-Key: {{apiKey}}

### Email Ticket
GET {{baseUrl}}?r=api/ticket/send-email&id={{bookId}}
X-Api-Key: {{apiKey}}


### SEARCH ISBN ---------------------------------------------------
GET {{baseUrl}}?r=api/isbn-service/search&isbn=9782070344130
X-Api-Key: {{apiKey}}

### SEARCH ISBN : NOT FOUND ---------------------------------------------------
GET {{baseUrl}}?r=api/isbn-service/search&isbn=11
X-Api-Key: {{apiKey}}

### SEARCH BOOK DESCRIPTION  (ISBN)
GET {{baseUrl}}?r=api/isbn-service/description&isbn=9782070344130
X-Api-Key: {{apiKey}}

### USER-BOOK - Create ---------------------------------------------
POST {{baseUrl}}?r=api/user-book/create&expand=book
Content-Type:application/json
X-Api-Key: {{apiKey}}

{
    "book": {
        "title": "test",
        "author": "Inconnu",
        "isbn" : "1224"
    },
    "userBook" : {
        "read_status": 2,
        "read_at": "2022-02-28"
    }
}

### USER-BOOK - Read All 
GET {{baseUrl}}?r=api/user-book&expand=book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### USER-BOOK - View One
GET {{baseUrl}}?r=api/user-book/view&id={{bookId}}&expand=book
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

### USER-BOOK - Update One
PUT {{baseUrl}}?r=api/user-book/update&id={{bookId}}&expand=book
Content-Type:application/json
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "book": {
        "title": "new title2",
        "subtitle": "new subtitle2",
        "isbn": "22222"
    },
    "userBook": {
        "rate": 4,
        "read_at": "2022-10-01"
    }
}

# read_at : to reset set its value to null or "" (empty string)

### USER-BOOK - delete One
DELETE {{baseUrl}}?r=api/user-book/delete&id={{bookId}}
X-Api-Key: {{apiKey}}
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

