
### Read All
GET {{baseUrl}}?r=api/book

### Read All - only field title
GET {{baseUrl}}?r=api/book&fields=title

### Read One by Id
GET {{baseUrl}}?r=api/book/view&id=1

### Read One by Id, only field title
GET {{baseUrl}}?r=api/book/view&id=1&fields=title


### show header info
HEAD {{baseUrl}}?r=api/book

### Create
POST {{baseUrl}}?r=api/book/create
Content-Type:application/json

{
    "id": "3",
    "title": "Babylon99",
    "author": "Inconnu"
}

### Update
# id query param is required - id property is optional unless 
# it should also be updated
PATCH {{baseUrl}}?r=api/book/update&id=3
Content-Type:application/json

{
    "id": "3",
    "title": "Babylon99...",
    "author": "Inconnu"
}

### Delete
DELETE {{baseUrl}}?r=api/book/delete&id=3
